import { strToU8, zipSync } from 'fflate';

import type { BrandKit } from '@/lib/contracts';
import { rasterizeSvg, triggerDownload } from '@/lib/export-svg';
import { buildPlainCss, buildShadcnTheme } from '@/lib/theme-export';

export type ThemeFormat = 'shadcn' | 'plain';

function slugify(name: string | undefined): string {
  const slug = (name ?? 'brand')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  return slug || 'brand';
}

function buildReadme(kit: BrandKit, format: ThemeFormat, themeFile: string): string {
  const name = kit.name ?? 'your brand';
  const usage =
    format === 'shadcn'
      ? `- ${themeFile}: replace (or merge into) your app's globals.css. It follows the shadcn / Tailwind v4 token shape, so your existing components pick up the brand colours automatically.\n- Load the fonts named in the file via next/font or a Google Fonts <link>.`
      : `- ${themeFile}: import this CSS anywhere. Use the tokens as var(--brand-primary), var(--brand-font-display), etc. The font @import is included at the top.`;
  return `${name} — brand kit
Generated by Deszyn.

Contents:
- logo.svg / logo.png / logo.jpg — your logo in all three formats
- ${themeFile} — your colours + fonts as a drop-in theme

Usage:
${usage}
`;
}

export async function downloadBrandKit(kit: BrandKit, format: ThemeFormat): Promise<void> {
  const slug = slugify(kit.name);
  const files: Record<string, Uint8Array> = {};

  if (kit.logo?.svg) {
    files[`${slug}/logo.svg`] = strToU8(kit.logo.svg);
    const [png, jpg] = await Promise.all([
      rasterizeSvg(kit.logo.svg, 'image/png'),
      rasterizeSvg(kit.logo.svg, 'image/jpeg'),
    ]);
    files[`${slug}/logo.png`] = new Uint8Array(await png.arrayBuffer());
    files[`${slug}/logo.jpg`] = new Uint8Array(await jpg.arrayBuffer());
  }

  const themeFile = format === 'shadcn' ? 'globals.css' : 'brand.css';
  const themeCss = format === 'shadcn' ? buildShadcnTheme(kit) : buildPlainCss(kit);
  files[`${slug}/${themeFile}`] = strToU8(themeCss);
  files[`${slug}/README.txt`] = strToU8(buildReadme(kit, format, themeFile));

  const zipped = zipSync(files, { level: 6 });
  triggerDownload(new Blob([zipped], { type: 'application/zip' }), `${slug}-brand-kit.zip`);
}
