import type { BrandColor, BrandKit } from '@/lib/contracts';

function colorOf(colors: BrandColor[], role: BrandColor['role'], fallback: string): string {
  return colors.find((c) => c.role === role)?.hex ?? fallback;
}

function fontOf(kit: BrandKit, role: 'display' | 'body' | 'mono', fallback: string): string {
  return kit.fonts.find((f) => f.role === role)?.family ?? fallback;
}

function googleFontsUrl(families: string[]): string {
  const params = families
    .filter((f, i, arr) => arr.indexOf(f) === i)
    .map((f) => `family=${f.trim().replace(/\s+/g, '+')}:wght@400;500;600;700`)
    .join('&');
  return `https://fonts.googleapis.com/css2?${params}&display=swap`;
}

/** shadcn / Tailwind v4 CSS-first theme (`:root` + `.dark` + `@theme inline`). */
export function buildShadcnTheme(kit: BrandKit): string {
  const name = kit.name ?? 'Brand';
  const primary = colorOf(kit.colors, 'primary', '#4F7BFF');
  const accent = colorOf(kit.colors, 'accent', '#9CBAFF');
  const surface = colorOf(kit.colors, 'surface', '#131316');
  const display = fontOf(kit, 'display', 'Plus Jakarta Sans');
  const body = fontOf(kit, 'body', 'Geist');
  const mono = fontOf(kit, 'mono', 'Geist Mono');

  return `@import "tailwindcss";
@import "tw-animate-css";

@custom-variant dark (&:is(.dark *));

/* Brand theme for ${name} — generated by Deszyn. Load the fonts below via next/font or a Google Fonts @import. */

:root {
  --background: #ffffff;
  --foreground: #0a0a0b;
  --card: #ffffff;
  --card-foreground: #0a0a0b;
  --popover: #ffffff;
  --popover-foreground: #0a0a0b;
  --primary: ${primary};
  --primary-foreground: #ffffff;
  --secondary: #f4f4f5;
  --secondary-foreground: #0a0a0b;
  --muted: #f4f4f5;
  --muted-foreground: #71717a;
  --accent: ${accent};
  --accent-foreground: #0a0a0b;
  --destructive: #e5484d;
  --border: #e4e4e7;
  --input: #e4e4e7;
  --ring: ${primary};
  --chart-1: ${primary};
  --chart-2: ${accent};
  --radius: 0.625rem;
  --font-sans: "${body}", ui-sans-serif, system-ui, sans-serif;
  --font-display: "${display}", ui-sans-serif, system-ui, sans-serif;
  --font-mono: "${mono}", ui-monospace, SFMono-Regular, monospace;
}

.dark {
  --background: ${surface};
  --foreground: #fafafa;
  --card: ${surface};
  --card-foreground: #fafafa;
  --popover: ${surface};
  --popover-foreground: #fafafa;
  --primary: ${primary};
  --primary-foreground: #ffffff;
  --secondary: #27272a;
  --secondary-foreground: #fafafa;
  --muted: #27272a;
  --muted-foreground: #a1a1aa;
  --accent: ${accent};
  --accent-foreground: #0a0a0b;
  --destructive: #e5484d;
  --border: #27272a;
  --input: #27272a;
  --ring: ${primary};
  --chart-1: ${primary};
  --chart-2: ${accent};
}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);
  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);
  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);
  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);
  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);
  --color-destructive: var(--destructive);
  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --font-sans: var(--font-sans);
  --font-display: var(--font-display);
  --font-mono: var(--font-mono);
}
`;
}

/** A minimal, framework-agnostic set of CSS custom properties. */
export function buildPlainCss(kit: BrandKit): string {
  const name = kit.name ?? 'Brand';
  const display = fontOf(kit, 'display', 'Plus Jakarta Sans');
  const body = fontOf(kit, 'body', 'Geist');
  const mono = fontOf(kit, 'mono', 'Geist Mono');

  const vars = kit.colors.map((c) => `  --brand-${c.role}: ${c.hex}; /* ${c.name} */`).join('\n');

  return `/* Brand tokens for ${name} — generated by Deszyn */
@import url('${googleFontsUrl([display, body])}');

:root {
${vars}
  --brand-font-display: "${display}", ui-sans-serif, system-ui, sans-serif;
  --brand-font-body: "${body}", ui-sans-serif, system-ui, sans-serif;
  --brand-font-mono: "${mono}", ui-monospace, monospace;
}
`;
}
